import streamlit as st
import random
import pandas as pd
from fpdf import FPDF
import datetime

# إعدادات أساسية
BAR_LENGTH = 12.0
ITERATIONS = 3000
diameters = [10,12,14,16,18,20,22,25]

# حساب وزن المتر الطولي لكل قطر
def weight_per_meter(d):
    return (d**2)/162

# خوارزمية تحسين قص القضبان
def optimize_cutting(lengths):
    best_solution = None
    min_waste = float('inf')
    min_bars = float('inf')

    for _ in range(ITERATIONS):
        shuffled = lengths[:]
        random.shuffle(shuffled)
        shuffled.sort(reverse=True)

        bars = []

        for length in shuffled:
            placed = False
            for bar in bars:
                if sum(bar) + length <= BAR_LENGTH:
                    bar.append(length)
                    placed = True
                    break
            if not placed:
                bars.append([length])

        waste = sum(BAR_LENGTH - sum(bar) for bar in bars)

        if waste < min_waste or (waste == min_waste and len(bars) < min_bars):
            min_waste = waste
            min_bars = len(bars)
            best_solution = bars

    return best_solution, waste

# توليد تقرير PDF
def generate_pdf(df, price=None):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, "Rebar Optimization Report", ln=True, align="C")
    pdf.ln(10)

    pdf.set_font("Arial", '', 12)
    pdf.cell(0, 10, f"Generated by: Civil Engineer Mustafa Harmoush", ln=True)
    pdf.cell(0, 10, f"Date: {datetime.date.today()}", ln=True)
    pdf.ln(5)

    # Table Header
    col_widths = [25, 25, 35, 35, 35, 25, 25]
    headers = ["Diameter", "Bars Used", "Required Weight (kg)", 
               "Used Weight (kg)", "Waste Weight (kg)", "Waste %", "Cost"]
    for i, header in enumerate(headers):
        pdf.cell(col_widths[i], 10, header, border=1)
    pdf.ln()

    # Table Rows
    for index, row in df.iterrows():
        pdf.cell(col_widths[0], 10, str(row["Diameter"]), border=1)
        pdf.cell(col_widths[1], 10, str(row["Bars Used"]), border=1)
        pdf.cell(col_widths[2], 10, str(row["Required Weight (kg)"]), border=1)
        pdf.cell(col_widths[3], 10, str(row["Used Weight (kg)"]), border=1)
        pdf.cell(col_widths[4], 10, str(row["Waste Weight (kg)"]), border=1)
        pdf.cell(col_widths[5], 10, str(row["Waste %"]), border=1)
        pdf.cell(col_widths[6], 10, str(row["Cost"]), border=1)
        pdf.ln()

    pdf.ln(10)
    pdf.cell(0, 10, "Signature: ____________________", ln=True)

    filename = f"Rebar_Report_{datetime.date.today()}.pdf"
    pdf.output(filename)
    return filename

# إعداد صفحة Streamlit
st.set_page_config(layout="wide")
st.title("Rebar Optimizer Pro")
st.subheader("Created by Civil Engineer Mustafa Harmoush")

# زر Reset لمسح كل البيانات
if st.button("Reset"):
    st.experimental_rerun()

# إدخال سعر الطن (اختياري)
price = st.number_input("Price per ton (optional)", min_value=0.0)

# إدخال بيانات الأطوال والكميات لكل قطر
data = {}
st.markdown("## Enter Rebar Data")

for d in diameters:
    with st.expander(f"Diameter {d} mm"):
        rows = st.session_state.get(f"rows_{d}", [{"Length":0.0, "Quantity":0}])
        new_rows = []
        for i, row in enumerate(rows):
            col1, col2 = st.columns(2)
            length = col1.number_input(f"Length of rebar (m) [{i+1}]", value=row["Length"], key=f"len_{d}_{i}")
            quantity = col2.number_input(f"Quantity [{i+1}]", value=row["Quantity"], key=f"qty_{d}_{i}", min_value=0)
            new_rows.append({"Length": length, "Quantity": quantity})
        st.session_state[f"rows_{d}"] = new_rows

        if st.button(f"Add Row for Diameter {d}"):
            st.session_state[f"rows_{d}"].append({"Length":0.0, "Quantity":0})
            st.experimental_rerun()

        # تحويل البيانات لكل قطر لقائمة أطوال
        lengths_list = []
        for r in st.session_state[f"rows_{d}"]:
            lengths_list.extend([r["Length"]]*r["Quantity"])
        if lengths_list:
            data[d] = lengths_list

# تشغيل الحساب عند الضغط على الزر
if st.button("Run Optimization"):

    results = []

    for d, lengths in data.items():

        solution, waste = optimize_cutting(lengths)

        total_required = sum(lengths)
        used_bars = len(solution)
        total_bar_length = used_bars * BAR_LENGTH

        wpm = weight_per_meter(d)

        required_weight = total_required * wpm
        used_weight = total_bar_length * wpm
        waste_weight = waste * wpm
        waste_percent = (waste / total_bar_length)*100

        cost = (used_weight/1000)*price if price else 0

        results.append([
            d,
            used_bars,
            round(required_weight,2),
            round(used_weight,2),
            round(waste_weight,2),
            round(waste_percent,2),
            round(cost,2)
        ])

    df = pd.DataFrame(results, columns=[
        "Diameter",
        "Bars Used",
        "Required Weight (kg)",
        "Used Weight (kg)",
        "Waste Weight (kg)",
        "Waste %",
        "Cost"
    ])

    st.success("Optimization Completed ✅")
    st.dataframe(df)

    # زر تحميل PDF
    pdf_file = generate_pdf(df, price)
    with open(pdf_file, "rb") as f:
        st.download_button(
            label="Download PDF Report",
            data=f,
            file_name=pdf_file,
            mime="application/pdf"
        )               
